import fs from 'node:fs';
import path from 'node:path';
import type { Connection } from '@ladybugdb/core';
import { queryAll } from './db.js';
import { formatRecords, sortRecords, type ContextRecord } from './record-format.js';

export const RULES_DIR = path.join('.cursor', 'rules');

/**
 * Marks a rule file as generated by specgraph. Pruning only ever deletes files
 * carrying this marker, so a rule the user wrote by hand is never touched.
 */
export const RULE_MARKER = '<!-- specgraph-managed-rule -->';

const FILE_PREFIX = 'specgraph-';

export interface FileRecords {
  file: string;
  /** True when `file` is a directory anchor — the rule then globs its subtree. */
  isDir: boolean;
  records: ContextRecord[];
}

function toRecord(row: Record<string, unknown>): ContextRecord {
  return {
    id: String(row['id']),
    kind: String(row['kind']),
    claim: String(row['claim']),
    because: row['because'] == null ? null : String(row['because']),
    provenance: String(row['provenance']),
    ref: row['ref'] == null ? null : String(row['ref']),
  };
}

/**
 * Group every live record by the file (or directory) its subjects live in.
 * DISTINCT is required: a record naming several symbols in one file yields one
 * row per ABOUT edge, and the per-file Map then collapses the two queries. A
 * directory subject (File node with kind 'dir') becomes a subtree-globbed rule.
 */
export async function fetchRecordsByFile(conn: Connection): Promise<FileRecords[]> {
  const queries = [
    `MATCH (r:Record)-[:ABOUT]->(c:CodeSymbol)
     WHERE r.live
     RETURN DISTINCT c.file_path AS file, 'source' AS fileKind, r.id AS id, r.kind AS kind,
                     r.claim AS claim, r.because AS because, r.provenance AS provenance, r.ref AS ref`,
    `MATCH (r:Record)-[:ABOUT]->(f:File)
     WHERE r.live
     RETURN DISTINCT f.id AS file, f.kind AS fileKind, r.id AS id, r.kind AS kind,
                     r.claim AS claim, r.because AS because, r.provenance AS provenance, r.ref AS ref`,
  ];

  const byFile = new Map<string, { isDir: boolean; records: Map<string, ContextRecord> }>();
  for (const cypher of queries) {
    const { rows } = await queryAll(conn, cypher);
    for (const row of rows) {
      const file = String(row['file']);
      if (!file || file === 'null') continue;
      let group = byFile.get(file);
      if (!group) {
        group = { isDir: String(row['fileKind']) === 'dir', records: new Map() };
        byFile.set(file, group);
      }
      const record = toRecord(row);
      if (!group.records.has(record.id)) group.records.set(record.id, record);
    }
  }

  return [...byFile.entries()]
    .map(([file, g]) => ({ file, isDir: g.isDir, records: sortRecords([...g.records.values()]) }))
    .sort((a, b) => a.file.localeCompare(b.file));
}

/** Stable, collision-free filename for a rule describing one file or module. */
export function ruleFileName(file: string): string {
  const slug = file.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return `${FILE_PREFIX}${slug}.mdc`;
}

/**
 * A rule with globs set and alwaysApply false is auto-attached by Cursor when a
 * matching file is in context — the only documented Cursor mechanism for
 * scoped knowledge, since no Cursor hook can inject context before an edit. A
 * directory anchor globs the whole subtree, so a module rule attaches to every
 * file beneath it.
 */
export function renderRule(file: string, records: ContextRecord[], isDir = false): string {
  const glob = isDir ? `${file}/**` : file;
  const heading = isDir ? `Known about module ${file}` : `Known about ${file}`;
  return [
    '---',
    `description: Knowledge records for ${file}`,
    `globs: ${glob}`,
    'alwaysApply: false',
    '---',
    '',
    `# ${heading}`,
    '',
    ...formatRecords(records, Infinity),
    '',
    'If your edit would contradict any of the above, surface the conflict before proceeding.',
    'Before you finish: if you chose between alternatives, hit a trap, or learned something durable, record it (`specgraph records add` or MCP `add_record` then `reindex`). Decisions left only in code or chat are lost between sessions.',
    '',
    RULE_MARKER,
    '',
  ].join('\n');
}

/** Delete specgraph-owned rule files that the current run did not write. */
function pruneStaleRules(rulesDir: string, current: Set<string>): string[] {
  if (!fs.existsSync(rulesDir)) return [];
  const pruned: string[] = [];
  for (const entry of fs.readdirSync(rulesDir, { withFileTypes: true })) {
    if (!entry.isFile() || current.has(entry.name)) continue;
    const filePath = path.join(rulesDir, entry.name);
    let owned = false;
    try {
      owned = fs.readFileSync(filePath, 'utf-8').includes(RULE_MARKER);
    } catch {
      // Unreadable — not ours to delete.
    }
    if (owned) {
      fs.rmSync(filePath, { force: true });
      pruned.push(entry.name);
    }
  }
  return pruned;
}

export interface WriteRulesResult {
  written: string[];
  pruned: string[];
}

export function writeRules(projectDir: string, groups: FileRecords[]): WriteRulesResult {
  const rulesDir = path.join(projectDir, RULES_DIR);
  const written: string[] = [];
  const names = new Set<string>();

  if (groups.length > 0) fs.mkdirSync(rulesDir, { recursive: true });

  for (const group of groups) {
    const name = ruleFileName(group.file);
    names.add(name);
    fs.writeFileSync(
      path.join(rulesDir, name),
      renderRule(group.file, group.records, group.isDir),
      'utf-8',
    );
    written.push(name);
  }

  return { written, pruned: pruneStaleRules(rulesDir, names) };
}
